[package]
name = "bacon-ls"
version = "0.1.0"
edition = "2021"
authors = ["Matteo Bigoi <bigo@crisidev.org"]
license-file = "LICENSE"

[dependencies]
once_cell = "1.19.0"
regex = "1.10.4"
serde_json = "1.0"
tokio = { version = "1.37", features = [
    "macros",
    "rt-multi-thread",
    "io-std",
    "io-util",
    "fs",
    "time",
] }
tower-lsp = "0.20"
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "env-filter",
    "fmt",
] }

[dev-dependencies]
test-log = { version = "0.2", features = ["trace"] }
httparse = "1.8"
similar-asserts = "1.4"
