name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: bacon_ls

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: cargo test
      env:
        RUST_LOG: debug,globset=warn
    - run: cargo fmt --all -- --check
    - run: cargo clippy
    - run: cargo build
    - run: npm ci
    - run: npm run lint
    - name: npx vsce package
      run: npx vsce package
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: cargo test
      env:
        RUST_LOG: debug,globset=warn
        RUST_BACKTRACE: 1
